### ISSUE TITLE
Issues after creating tethys environment

### ISSUE THREAD

**Issue by hello-deepak** [tethysplatform/tethys#589] opened 2020-08-26 10:47 UTC
I created a tethys_test environment using the command :  `conda create -n tethys_test -c tethysplatform -c conda-forge tethys-platform`

After that I activate the tethys_test environment: `conda activate tethys_test`

Then I I did the `tethys --help` after activating my tethys_test environment. I got the following error:
Every tethys command is giving the same error.

## Error

Traceback (most recent call last):
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/http/client.py", line 1028, in _send_output
    self.send(msg)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/http/client.py", line 968, in send
    self.connect()
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/http/client.py", line 1028, in _send_output
    self.send(msg)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/http/client.py", line 968, in send
    self.connect()
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/docker/api/client.py", line 205, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/docker/api/client.py", line 228, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deepak/conda/anaconda/envs/tethys_test/bin/tethys", line 6, in <module>
    from tethys_cli import tethys_command
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/tethys_cli/__init__.py", line 16, in <module>
    from tethys_cli.docker_commands import add_docker_parser
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/tethys_cli/docker_commands.py", line 59, in <module>
    class ContainerMetadata(ABC):
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/tethys_cli/docker_commands.py", line 69, in ContainerMetadata
    _docker_client = docker.from_env()
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/docker/client.py", line 85, in from_env
    timeout=timeout, version=version, **kwargs_from_env(**kwargs)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/docker/client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/docker/api/client.py", line 188, in __init__
    self._version = self._retrieve_server_version()
  File "/home/deepak/conda/anaconda/envs/tethys_test/lib/python3.7/site-packages/docker/api/client.py", line 213, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by ezrajrice** [comment] 2020-08-26 15:36
@hello-deepak Sorry you're having difficulties installing Tethys Platform. Reviewing your error logs shows that the following packages had some error:
* docker
* urllib3
* requests

Could you check what versions of those libraries you have installed in the tethys_test environment? I am assuming you followed the production installation instructions, correct? This will help us rule out a dependency issue and we can dive into where and why Tethys is having problems.

**Comment by ShakyaKiran** [comment] 2020-08-26 16:47
I have similar issue with Ubuntu.  

Ubuntu version: 18.04
urllib3 version: 1.25.10
docker version: 4.3.1
requests version: 2.24.0

**Comment by swainn** [comment] 2020-08-26 19:43
I can confirm the same issue if I stop the Docker daemon. It looks like a connection to Docker is being attempted when `tethys_cli` is imported. @sdc50 @SarvaPulla are you having the same issue?

**Comment by swainn** [comment] 2020-08-26 19:46
As a temporary workaround, you could install Docker: https://docs.docker.com/engine/install/ubuntu/

**Comment by swainn** [comment] 2020-09-08 17:11
@sdc50 could this issue be related to the updates to the Docker command you did in 3.0?

**Comment by rfun** [comment] 2020-09-10 21:32
@swainn : We are starting to notice this on fresh tethys environments within our lab as well. Do you guys have a fix for this yet?

**Comment by sdc50** [comment] 2020-09-10 22:15
> @sdc50 could this issue be related to the updates to the Docker command you did in 3.0?

Yes, it looks like this is related to the Docker command refactor. In particular [this line](https://github.com/tethysplatform/tethys/blob/master/tethys_cli/docker_commands.py#L69) is the culprit. 

I believe the point was to make it slightly more efficient by instantiating `_docker_client` at the class level. As @swainn has already pointed out if you have the docker daemon running then it works. However, if you don't have it running then when it tries to instantiate the docker client then it raises an exception. Since it's trying to instantiate it in the class definition then this error occurs on import which is why any `tethys` command is causing the error. I should be able to submit a hotfix shortly.

**Comment by swainn** [comment] 2020-09-14 15:44
@sdc50 this issue is also the cause of our failing docker builds (b/c the Docker daemon is not available inside the Docker image that is being built).

**Comment by swainn** [comment] 2020-09-14 17:25
We just released a patch for 3.1.1. You should be able to install from conda now. @hello-deepak can you update and verify the patch fixes this issue?

**Closed** 2020-09-15 18:30 UTC
Labels: bug, hotfix

**Comment by swainn** [comment] 2020-09-15 18:31
Just merged the fix for master as well.
